[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', '@openzeppelin/=lib/openzeppelin-contracts/', 'solmate/=lib/solmate/src/']
solc-version = "0.8.13"

# See more config options https://github.com/gakonst/foundry/tree/master/config